### ISSUE TITLE
tensorboard not specified as a requirement in setup.py

### ISSUE THREAD

**Issue by michael-conrad** [lmnt-com/diffwave#20]
tensorboard not specified as a requirement in setup.py

```
python -m diffwave --help
Traceback (most recent call last):
  File "/home/muksihs/.conda/envs/cherokee-diffwave/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/muksihs/.conda/envs/cherokee-diffwave/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/muksihs/.conda/envs/cherokee-diffwave/lib/python3.7/site-packages/diffwave/__main__.py", line 20, in <module>
    from diffwave.learner import train, train_distributed
  File "/home/muksihs/.conda/envs/cherokee-diffwave/lib/python3.7/site-packages/diffwave/learner.py", line 22, in <module>
    from torch.utils.tensorboard import SummaryWriter
  File "/home/muksihs/.conda/envs/cherokee-diffwave/lib/python3.7/site-packages/torch/utils/tensorboard/__init__.py", line 1, in <module>
    import tensorboard
ModuleNotFoundError: No module named 'tensorboard'
```

**Comment by sharvil** [comment]
Yeah, it's only required for training, not inference, so I don't think it should be a hard dependency. Thanks for the suggestion!
